### ISSUE TITLE
Need a lil help

### ISSUE THREAD

**Issue by Bhavye-Malhotra** [RhinoCodes/ArchLive#1]
So i downloaded your dwm iso and it booted perfectly👍
now i am asking that do i have to like make partition and all if so pls guide me i am a newbie  😄

**Comment by Szybet** [comment]
So if i understand, you want to install arch linux?

**Comment by Bhavye-Malhotra** [comment]
Yes i mean its a live instance so to make it persistent i need to install it on disk right ?

**Comment by Szybet** [comment]
https://wiki.archlinux.org/index.php/Installation_guide#Partition_the_disks
Here is anything explained.
For more questions, join our discord.
(becouse its not a issue with the isos)
